### ISSUE TITLE
(&) operator silently drops edges

### ISSUE THREAD

**Issue by osbugs** [haskell/fgl#27] opened 2016-02-24 14:30 UTC
When adding a Context with the (&) operator to an existing graph, it seems as if incoming edges are silenty dropped if the edge references a node that is not yet in the graph. However, if the outgoing edge is referencing a node that is not yet in the graph, the edge is retained. This behaviour seems inconsistent to me.

Example:
```
> (([((), 1)], 2, (), [((), 3)]) & empty :: Gr () ())
mkGraph [(2,())] [(2,3,())]
```
Here, the edge from 2 to 3 is in the graph, the edge from 1 to 2 isn't. Even after adding node 1 into the graph, the information is lost:
```
> insNode (1, ()) $ (([((), 1)], 2, (), [((), 3)]) & empty :: Gr () ())
mkGraph [(1,()),(2,())] [(2,3,())]
```

If this behaviour is by intent, it should be at least documented.

**Comment by ivan-m** [comment] 2016-02-25 01:24
The former behaviour is correct; the latter is a bug.

That is: a Context should only refer to either a Node already in a graph or the node in the Context itself (for loops).

I'm finishing moving at the moment so I'll have a look at this once I've cleared enough space to set my computer up at home :p

**Comment by osbugs** [comment] 2016-02-25 05:48
Thanks. In the meantime, I have created a pull request to update the documentation (#28).

**Comment by ivan-m** [comment] 2016-05-24 21:38
Closed in favour of #28

**Closed by ivan-m** 2016-05-24 21:38 UTC

**Comment by osbugs** [comment] 2016-05-29 04:58
Is it a good idea to leave the bug in the code, and just document the bug in the line of issue #28?

**Comment by ivan-m** [comment] 2016-05-29 05:52
Well, it's only a bug in the sense of fgl not throwing an error when this happens rather than silently doing losing information.

However, that would require either a) throwing an error (which is usually undesirable) or b) returning a `Maybe`, which makes the code messier.

(I have heard of graph manipulation being akin to pointer arithmetic due to this nature: you either have good APIs and nice performance with lots of ways to throw errors/have unexpected behaviour, or else be really safe but with a horrible API and lots of checking slowing the code down.)

I think a warning of this behaviour in the documentation for `&` (and potentially `buildGr`) would suffice; at the very least it's probably the lesser of all the evils.
